### ISSUE TITLE
Upload/Download requests gets cancled 

### ISSUE THREAD

**Issue by Exlord** [nesk/speedtest#14]
Hi, i am trying to setup a speed test.
the download and upload requests are getting cancelled .
you can check my code here : http://farhadadeli.ir/SpeedTest
can you help? it's kind of urgent ...
I am using the provided php file as the server.

I used the code from your "How to use" witch is not working, but then i used the "main.js" file from your own sample site and that one works.

**Comment by Nesk** [comment]
So, is there any issues right now? I tried your example and everything seems to work for me (although I got some pretty bad results with Firefox).

Should I consider the code from the “How to use” section as broken?

**Comment by Exlord** [comment]
yes, the code from the “How to use” section is broken, download and upload requests gets cancelled right after they start and the result is ```null``` or ```0```

**Comment by Nesk** [comment]
Thank you for your feedback, I will work on this :)
