### ISSUE TITLE
Download and Upload tests bad works on local server (localhost). Speed no limit.

### ISSUE THREAD

**Issue by thejustsoul** [nesk/speedtest#24]
Download and Upload tests bad works on *local server*  (localhost). Turns out endless test with large numbers (newer stop?).

> [Download] The minimum delay of 8.000 seconds has not been reached
> [Download] Restarting measures with 163840.000 MB of data...
etc...

Tested in `Firefox` and `Chromium` latest version.
Server `Apache 2.4` on Windows.

**Comment by nesk** [comment]
SpeedTest isn't built to handle very high bandwidths like the ones you can obtain on a local network, this is currently limited by the browsers. Latency measures should work, but forget about the bandwidth ones.
